# Generated by Django 5.2.5 on 2025-10-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_available_tickets_event_max_tickets_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_tickets',
            field=models.PositiveIntegerField(),
        ),
    ]
