# Generated by Django 5.2.5 on 2025-08-22 12:12

import django.db.models.deletion
import mainapp.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='partyimage',
            name='party',
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=mainapp.models.event.get_image_filename)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.event')),
            ],
        ),
        migrations.DeleteModel(
            name='Party',
        ),
        migrations.DeleteModel(
            name='PartyImage',
        ),
    ]
