# Generated by Django 5.2.5 on 2025-09-02 11:42

import django.db.models.deletion
import mainapp.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_event_remove_partyimage_party_eventimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.FileField(upload_to=mainapp.models.event.get_video_filename)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='mainapp.event')),
            ],
        ),
    ]
